# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_auto_20180719_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cmessage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mcomments', to='wall_app.Message'),
        ),
    ]
