# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_comment_cmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmessage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcomments', to='wall_app.Message'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wall_app.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wall_app.User'),
        ),
    ]
